dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
global:
  – DBUS_SESSION_BUS_ADDRESS=/dev/null
  – DISPLAY=:99.0
  – CHROME_BIN=chromium-browser
install:
  - npm install
script:
- npm test