dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
global:
  – DBUS_SESSION_BUS_ADDRESS=/dev/null
  – DISPLAY=:99.0
  – CHROME_BIN=chromium-browser
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 6
install:
  - npm install
script:
- ng test